# Generated by Django 3.0.3 on 2020-02-26 12:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name_Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=128, verbose_name='姓名')),
                ('picture', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
