# Generated by Django 3.0.3 on 2020-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_picture',
            name='picture',
            field=models.CharField(max_length=1280, verbose_name='picture'),
        ),
    ]
