# Generated by Django 3.0.3 on 2020-02-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDataManagement', '0003_auto_20200227_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_picture',
            name='picture',
            field=models.TextField(verbose_name='picture'),
        ),
    ]
