# Generated by Django 3.0.3 on 2020-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDataManagement', '0004_auto_20200227_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_picture',
            name='picture',
            field=models.CharField(max_length=128, verbose_name='picture'),
        ),
    ]
